# Generated by Django 4.1.7 on 2023-04-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='my_user',
        ),
    ]
