# Generated by Django 4.1.7 on 2023-04-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usermodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='created_at',
        ),
    ]
