# Generated by Django 4.1.7 on 2023-04-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_usermodel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password2',
        ),
        migrations.CreateModel(
            name='UserModelCheck',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.usermodel')),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
            ],
            bases=('user.usermodel',),
        ),
    ]
